name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src/Venflow
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/Venflow
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./src/Venflow
            
